export const EmployeeModel = {
    employeeID: '',
    firstName: '',
    middleName: '',
    lastName: '',
    secondLastName: '',
    phoneNumber: '',
    genderID: '',
    docID: '',
    docNumber: '',
    photoUrl: null,
    birthDate: new Date(),
    bloodTypeID: '',
    stateID: null,
    cityID: null,
    sectorID: null,
    suburbID: null,
    address: '',
    gabachSize: null,
    shirtSize: null,
    divisionID: null,
    areaID: null,
    departmentID: null,
    jobID: null,
    line: null,
    supervisor: null,
    hireDate: new Date(),
    endDate: null,
    isActive: true,
    partnerName: '',
    partnerage: 0,
    companyID: 1,
    contractTypeID: '',
    payrollTypeID: '',
    shiftID: '',
    educationLevelID: '',
    educationGrade: '',
    transportTypeID: '',
    maritalStatusID: '',
    nationality: '',
    evaluationStep: false,
    incapacitated: false,
    salary: 0,
    relatives: false
}

export const EmployeeRequiredFields = {
    firstName: 'Primer nombre',
    lastName: 'Primer apellido',
    phoneNumber: 'Teléfono',
    genderID: 'Genero',
    docID: 'Tipo de documento',
    docNumber: 'Identidad',
    birthDate: 'Fecha de nacimiento',
    bloodTypeID: 'Tipo de sangre',
    stateID: 'Estado',
    cityID: 'Ciudad',
    sectorID: 'Sector',
    suburbID: 'Suburbio',
    address: 'Dirección',
    gabachSize: 'Tamaño de gabacha',
    shirtSize: 'Tamaño de camisa',
    divisionID: 'División',
    areaID: 'Área',
    departmentID: 'Departamento',
    jobID: 'Puesto',
    hireDate: 'Fecha de contratación',
    isActive: 'Activo',
    companyID: 'Compañía',
    contractTypeID: 'Tipo de contrato',
    payrollTypeID: 'Tipo de pago',
    shiftID: 'Turno',
    educationLevelID: 'Nivel de educacion ',
    educationGrade: 'Grado de educacion',
    transportTypeID: 'Tipo de transporte',
    maritalStatusID: 'Estado marital',
    nationality: 'Nacionalidad',
    evaluationStep: 'Paso de evaluación'
}

export const ChildrenModel = {
    childrenID: '',
    firstName: '',
    middleName: '',
    lastName: '',
    secondLastName: '',
    birthDate: new Date(),
    birthCert: '',
    genderID: '',
    genderName: ''
}

export const FamilyInformationModel = {
    familyInfoID: '',
    relativesTypeID: '',
    relativesTypeDesc: '',
    firstName: '',
    middleName: '',
    lastName: '',
    secondLastName: '',
    age: ''
}

export const EcontactsModel = {
    econtactID: '',
    firstName: '',
    middleName: '',
    lastName: '',
    secondLastName: '',
    stateID: null,
    cityID: null,
    sectorID: null,
    suburbID: null,
    relativesTypeID: '',
    relativesTypeDesc: '',
    phoneNumber: '',
}

export const BeneficiariesModel = {
    beneficiaryID: '',
    firstName: '',
    middleName: '',
    lastName: '',
    secondLastName: '',
    relativesTypeID: '',
    relativesTypeDesc: '',
    percentage: 0,
    phoneNumber: '',
}

export const AuxRelativeModel = {
    auxRelativeID: '',
    relativesTypeID: '',
    newEmployee: '',
    relativesTypeDesc: '',
    employeeID: '',
    completeName: '',
}